namespace Store.Domain;

/// <summary>
///     Denotes a <see cref="Message" />'s position within the <see cref="IMessageStore" />.
/// </summary>
/// <remarks>
///     Generated by the <see cref="IMessageStore" />.
/// </remarks>
public class GlobalPosition : TinyType<ulong>
{
    public GlobalPosition(ulong value) : base(value)
    {
    }

    public static implicit operator GlobalPosition(ulong source) => new(source);
}

/// <summary>
///     Denotes a <see cref="Message" />'s position within its <see cref="Stream" />.
/// </summary>
/// <remarks>
///     Generated by the <see cref="IMessageStore" />.
/// </remarks>
public class Position : TinyType<uint>
{
    public Position(uint value) : base(value)
    {
    }

    public static implicit operator Position(uint source) => new(source);
}

/// <summary>
///     Data about a <see cref="Message" />.
/// </summary>
/// <param name="GlobalPosition"></param>
/// <param name="Position"></param>
/// <param name="Timestamp">When a <see cref="Message" /> was written to the <see cref="IMessageStore" />.</param>
public record Metadata(GlobalPosition GlobalPosition, Position Position, DateTime Timestamp);
